"""empty message

Revision ID: 3e76abcd9ef4
Revises: 
Create Date: 2017-10-30 17:37:53.995626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e76abcd9ef4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.Binary(), nullable=False),
    sa.Column('type_user', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(length=25), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('street', sa.String(length=150), nullable=False),
    sa.Column('number', sa.String(length=6), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=150), nullable=False),
    sa.Column('school_name', sa.String(length=150), nullable=False),
    sa.Column('grade', sa.String(length=30), nullable=False),
    sa.Column('course_load', sa.Integer(), nullable=False),
    sa.Column('conclusion', sa.String(length=10), nullable=False),
    sa.Column('observation', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birth_date', sa.String(length=10), nullable=True),
    sa.Column('alternative_email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('cellphone', sa.String(length=20), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('street', sa.String(length=150), nullable=False),
    sa.Column('number', sa.String(length=6), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post', sa.String(length=150), nullable=False),
    sa.Column('company', sa.String(length=150), nullable=False),
    sa.Column('entry_date', sa.String(length=10), nullable=False),
    sa.Column('departure_date', sa.String(length=10), nullable=True),
    sa.Column('tasks', sa.String(length=250), nullable=False),
    sa.Column('observation', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('works')
    op.drop_table('jobs')
    op.drop_table('infos')
    op.drop_table('courses')
    op.drop_table('companies')
    op.drop_table('users')
    # ### end Alembic commands ###
